#!/bin/bash
# description: Controls Ethercis Server
# processname: ecis-server
#
# SCRIPT created 15-10-2015, CCH
# Rev 1.1. September 2016. Uses v1.1.0 SNAPSHOT
# Rev 1.1.2 April 2018 Uses v1.1.2 SNAPSHOT
#-----------------------------------------------------------------------------------
UNAME=`uname`
HOSTNAME=`hostname`
export ECIS_DEPLOY_BASE=/opt/ecis
export SYSLIB=${ECIS_DEPLOY_BASE}/lib/system
export COMMONLIB=${ECIS_DEPLOY_BASE}/lib/common
export APPLIB=${ECIS_DEPLOY_BASE}/lib/application
export LIB=${ECIS_DEPLOY_BASE}/lib/deploy

# Mailer configuration
ECIS_MAILER=echo

# use the right jvm library depending on the OS
# NB: EtherCIS requires java 8
if [ :${UNAME}: = :Linux: ];
then
  JAVA_HOME=/opt/jdk1.8.0_60/jre
fi
if [ :${UNAME}: = :SunOS: ];
then
  JAVA_HOME=/jdk1.8.0_60/jre
fi

#force to use IPv4 so Jetty can bind to it instead of IPv6...
export _JAVA_OPTIONS="-Djava.net.preferIPv4Stack=true"

# runtime parameters
export JVM=${JAVA_HOME}/bin/java
export RUNTIME_HOME=/opt/ecis
export RUNTIME_ETC=/etc/opt/ecis
export RUNTIME_LOG=/var/opt/ecis
export RUNTIME_DIALECT=EHRSCAPE  #specifies the query dialect used in HTTP requests (REST)
export SERVER_PORT=8080 # the port address to bind to
export SERVER_HOST=178.62.71.220 # the network address to bind to

export MAILER_CONF=${RUNTIME_ETC}/xcmail.cf

export JOOQ_DIALECT=POSTGRES
JOOQ_DB_PORT=5433
JOOQ_DB_HOST=localhost
JOOQ_DB_SCHEMA=ethercis
export JOOQ_URL=jdbc:postgresql://${JOOQ_DB_HOST}:${JOOQ_DB_PORT}/${JOOQ_DB_SCHEMA}
export JOOQ_DB_LOGIN=postgres
export JOOQ_DB_PASSWORD=postgres

CLASSPATH=./:\
${JAVA_HOME}/lib:\
${LIB}/1.1.2/*:\
${APPLIB}/ecis-dependencies/*:\
${APPLIB}/openehr-java-lib/*

# launch server
# ecis server is run as user ethercis
su - ethercis << _ECIS
case "$1" in
  start)
    echo "ethercis startup"
     ( ${ECIS_MAILER} ${MAILER_CONF} "EtherCIS Startup" "Manual invocation of server startup" > /dev/null )&
    (
	${JVM} \
	-Xmx256M \
	-Xms256M \
	-server \
	-XX:-EliminateLocks \
	-XX:-UseVMInterruptibleIO \
    -XX:+HeapDumpOnOutOfMemoryError \
	-cp ${CLASSPATH} \
	-Djava.util.logging.config.file=${RUNTIME_ETC}/logging.properties \
	-Dlog4j.configurationFile=file:${RUNTIME_ETC}/log4j.xml \
	-Djava.net.preferIPv4Stack=true \
	-Djava.awt.headless=true \
	-Djdbc.drivers=org.postgresql.Driver \
    	-Dserver.node.name=vm01.ethercis.org \
    	-Dfile.encoding=UTF-8 \
    	-Djava.rmi.server.hostname=${SERVER_HOST} \
	-Djooq.dialect=${JOOQ_DIALECT} \
	-Djooq.url=${JOOQ_URL} \
	-Djooq.login=${JOOQ_DB_LOGIN} \
	-Djooq.password=${JOOQ_DB_PASSWORD} \
	-Druntime.etc=${RUNTIME_ETC} \
	 com.ethercis.vehr.Launcher \
	-propertyFile /etc/opt/ecis/services.properties \
    	-server_host 178.62.71.220 \
    	-server_port 8080 \
 2>> ${RUNTIME_LOG}/ethercis_test.log >> ${RUNTIME_LOG}/ethercis_test.log &    )&
    ;;
  stop)
    ( ${ECIS_MAILER} ${MAILER_CONF} "Ethercis Stop" "Manual invocation of server STOP" > /dev/null )&
    echo "ethercis shutdown"
    pkill java
    ;;
  restart)
    ( ${ECIS_MAILER} ${MAILER_CONF} "Ethercis Restart" "Manual invocation of server RESTART" )&
    echo "ethercis restarting"
    $0 stop
    $0 start
    ;;
  clean)
    (${ECIS_MAILER} ${MAILER_CONF} "Ethercis CLEAR" "Manual invocation of server Clear logs" > dev/null )&
    echo "ethercis clear"
    $0 stop
	rm -rf {RUNTIME_LOG}/ethercis_test.log
    ;;
  *)
    echo "Usage: ecis-server {start|stop|restart|clean}"
    exit 1
esac
_ECIS
exit 0
# end of file