FROM centos:7

MAINTAINER Alessandro Fael Garcia <alessfg@hotmail.com>, Christian Chevalley <christian@ripple.foundation>

LABEL EtherCIS-Version="1.2.0" \
Description="Docker image for the EtherCIS database on PostgreSQL 10"

